Update Package Names for Fedora
scipy/scipy.org pull request #472
Opened 2022-04-19 17:23 UTC by abe-101

Following the installation guide to install scipy system wide on fedora:
`sudo dnf install numpy scipy python-matplotlib ipython python-pandas sympy python-nose atlas-devel`
Produces the error:
```
No match for argument: scipy
No match for argument: sympy
Error: Unable to find a match: scipy sympy
```
I've updated the guide to include the correct package names:
`sudo dnf install python-numpy python-scipy python-matplotlib ipython python-pandas python-sympy python-nose atlas-devel`

2022-04-19 17:25 UTC, tupui approved these changes
Thank you @abe-101. LGTM but I am not a Fedora user.

@jarrodmillman I think you use Fedora right? Anything else to do here?

2022-04-19 17:26 UTC, tupui commented
Here https://developer.fedoraproject.org/tech/languages/python/scipy.html I can see that they use `python3-...` instead. Not sure what's preferred.

2022-04-19 17:49 UTC, abe-101 commented
> Here https://developer.fedoraproject.org/tech/languages/python/scipy.html I can see that they use `python3-...` instead. Not sure what's preferred.
> 
> Also I thought we cleaned this page a bit more than that. We are still referring to other packages than SciPy. cc @melissawm

It seems that `python-...` will point to the version of python the user is running. I'm not sure what the preferred way is.
Based on a chat I had with other fedora users it seems `python3-...` would be "more correct".
I've gone ahead and updated it.
Thank you @tupui for pointing it out.

2022-04-24 17:01 UTC, jarrodmillman commented
I would use `python3-ipython` as well.  We don't need `python3-nose` or `atlas-devel`.

The whole page needs some attention, but that can be in a separate PR.

2022-04-24 17:04 UTC, jarrodmillman requested changes

2022-04-24 17:04 UTC, jarrodmillman commented on content/en/install.md
> +    sudo dnf install python3-numpy python3-scipy python3-matplotlib ipython python3-pandas python3-sympy python3-nose atlas-devel
```suggestion
    sudo dnf install python3-numpy python3-scipy python3-matplotlib python3-ipython python3-pandas python3-sympy python3-pytest
```

2022-04-24 17:05 UTC, jarrodmillman commented
I would also change the heading from `Fedora 22 and later` to `Fedora`.

2022-04-24 20:21 UTC, jarrodmillman approved these changes

2022-04-24 20:22 UTC, jarrodmillman commented
Thanks!

2022-04-24 20:22 UTC, merged